# Generated by Django 3.2 on 2022-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('PR', 'Обрабатывается'), ('STF', 'Отправлен на сборку'), ('ST', 'Передан в службу доставки'), ('PD', 'Оплачен, ожидает отправки'), ('RD', 'Доставлен'), ('CD', 'Отменён')], default='PR', max_length=3, verbose_name='статус заказа'),
        ),
    ]
